`timescale 1ns/1ps

// Deployment boundary for the cache datapath.  Research counters, event taps,
// and debug state intentionally terminate here so synthesis can prune any
// observation-only logic that does not participate in cache behaviour.
module l1d_cache_deploy #(
    parameter integer ADDR_WIDTH       = 64,
    parameter integer DATA_WIDTH       = 64,
    parameter integer LINE_BYTES       = 16,
    parameter integer NUM_SETS         = 8,
    parameter integer NUM_WAYS         = 2,
    parameter integer VICTIM_ENTRIES   = 4,
    // The dated deployment gates currently fail for every speculative
    // variant, so the safe deploy default is the optimized PF0 datapath.
    // Research/P3 configurations remain available through explicit overrides.
    parameter integer ENABLE_PREFETCH  = 0,
    parameter integer PREFETCH_POLICY  = 1,
    parameter integer PF_OPT_LEVEL     = 1,
    parameter integer PF_USE_STREAM    = (PF_OPT_LEVEL >= 2),
    parameter integer PF_USE_ADAPTIVE  = (PF_OPT_LEVEL >= 2),
    parameter integer PF_USE_SHADOW    = (PF_OPT_LEVEL >= 3),
    parameter integer PF_USE_MSHR      = (PF_OPT_LEVEL >= 3),
    parameter integer PF_IDLE_GUARD    = 2,
    parameter integer PF_EPOCH_DEMANDS = 256,
    parameter integer PF_OFF_DEMANDS   = 512,
    parameter integer PF_PROBE_BUDGET  = 8,
    parameter integer PF_PROBE_REFILL  = 16,
    parameter integer PF_ON_REFILL     = 8,
    parameter integer VC_FORMAT_IN_SWAP = 1
) (
    input  logic                         clk,
    input  logic                         rst_n,

    input  logic                         cfg_prefetch_enable,
    input  logic                         cfg_next_line_enable,

    input  logic                         cpu_req_valid,
    output logic                         cpu_req_ready,
    input  logic [ADDR_WIDTH-1:0]        cpu_req_addr,
    input  logic                         cpu_req_write,
    input  logic [1:0]                   cpu_req_size,
    input  logic                         cpu_req_unsigned,
    input  logic [DATA_WIDTH-1:0]        cpu_req_wdata,

    output logic                         cpu_rsp_valid,
    input  logic                         cpu_rsp_ready,
    output logic [DATA_WIDTH-1:0]        cpu_rsp_rdata,
    output logic                         cpu_rsp_error,
    output logic [1:0]                   cpu_rsp_error_cause,

    output logic                         mem_req_valid,
    input  logic                         mem_req_ready,
    output logic                         mem_req_write,
    output logic [ADDR_WIDTH-1:0]        mem_req_addr,
    output logic [(LINE_BYTES*8)-1:0]    mem_req_wdata,
    input  logic                         mem_rsp_valid,
    input  logic [(LINE_BYTES*8)-1:0]    mem_rsp_rdata,

    output logic                         cache_idle
);
    l1d_cache #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH),
        .LINE_BYTES(LINE_BYTES),
        .NUM_SETS(NUM_SETS),
        .NUM_WAYS(NUM_WAYS),
        .VICTIM_ENTRIES(VICTIM_ENTRIES),
        .ENABLE_PREFETCH(ENABLE_PREFETCH),
        .PREFETCH_POLICY(PREFETCH_POLICY),
        .PF_OPT_LEVEL(PF_OPT_LEVEL),
        .PF_USE_STREAM(PF_USE_STREAM),
        .PF_USE_ADAPTIVE(PF_USE_ADAPTIVE),
        .PF_USE_SHADOW(PF_USE_SHADOW),
        .PF_USE_MSHR(PF_USE_MSHR),
        .PF_IDLE_GUARD(PF_IDLE_GUARD),
        .PF_EPOCH_DEMANDS(PF_EPOCH_DEMANDS),
        .PF_OFF_DEMANDS(PF_OFF_DEMANDS),
        .PF_PROBE_BUDGET(PF_PROBE_BUDGET),
        .PF_PROBE_REFILL(PF_PROBE_REFILL),
        .PF_ON_REFILL(PF_ON_REFILL),
        .VC_FORMAT_IN_SWAP(VC_FORMAT_IN_SWAP)
    ) u_cache (
        .clk(clk),
        .rst_n(rst_n),
        .cfg_prefetch_enable(cfg_prefetch_enable),
        .cfg_next_line_enable(cfg_next_line_enable),
        .ext_prefetch_valid(1'b0),
        .ext_prefetch_ready(),
        .ext_prefetch_addr({ADDR_WIDTH{1'b0}}),
        .cpu_req_valid(cpu_req_valid),
        .cpu_req_ready(cpu_req_ready),
        .cpu_req_addr(cpu_req_addr),
        .cpu_req_write(cpu_req_write),
        .cpu_req_size(cpu_req_size),
        .cpu_req_unsigned(cpu_req_unsigned),
        .cpu_req_wdata(cpu_req_wdata),
        .cpu_rsp_valid(cpu_rsp_valid),
        .cpu_rsp_ready(cpu_rsp_ready),
        .cpu_rsp_rdata(cpu_rsp_rdata),
        .cpu_rsp_error(cpu_rsp_error),
        .cpu_rsp_error_cause(cpu_rsp_error_cause),
        .mem_req_valid(mem_req_valid),
        .mem_req_ready(mem_req_ready),
        .mem_req_write(mem_req_write),
        .mem_req_addr(mem_req_addr),
        .mem_req_wdata(mem_req_wdata),
        .mem_rsp_valid(mem_rsp_valid),
        .mem_rsp_rdata(mem_rsp_rdata),
        .stat_cpu_hits(),
        .stat_cpu_misses(),
        .stat_victim_hits(),
        .stat_writebacks(),
        .stat_prefetch_fills(),
        .stat_prefetch_useful(),
        .stat_prefetch_useless(),
        .stat_prefetch_pollution(),
        .stat_prefetch_dropped(),
        .cache_idle(cache_idle),
        .event_cpu_access(),
        .event_cpu_hit(),
        .event_cpu_miss(),
        .event_victim_hit(),
        .event_writeback(),
        .event_prefetch_fill(),
        .event_prefetch_useful(),
        .event_prefetch_useless(),
        .event_prefetch_pollution(),
        .event_prefetch_dropped(),
        .debug_state(),
        .debug_req_is_prefetch(),
        .stat_pf_candidates(),
        .stat_pf_admitted(),
        .stat_pf_issued(),
        .stat_pf_returned(),
        .stat_pf_installed(),
        .stat_pf_merged(),
        .stat_pf_discarded(),
        .stat_pf_cancelled(),
        .stat_pf_unused_evicted(),
        .stat_pf_vc_bypass(),
        .stat_pf_caused_writebacks(),
        .stat_pf_demand_block_cycles(),
        .stat_pf_true_help(),
        .stat_pf_true_pollution(),
        .stat_pf_suppressed_quota(),
        .stat_pf_suppressed_unsafe(),
        .stat_pf_same_line_coalesced(),
        .debug_pf_controller_state(),
        .debug_pf_mshr_valid(),
        .debug_pf_mshr_addr(),
        .debug_pf_mshr_confidence()
    );
endmodule
